#!/usr/bin/env bash
# Point Hermes at local Ollama (non-interactive). Writes ~/.hermes config from .env.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
[[ -f "$ROOT/.env" ]] && source "$ROOT/.env"

MODEL="${OLLAMA_MODEL:-coder-64k}"
HOST_PORT="${OLLAMA_HOST:-127.0.0.1:11434}"
BASE_URL="http://${HOST_PORT}/v1"
CTX="$(bash "$ROOT/ollama/default_num_ctx.sh")"
export OLLAMA_NUM_CTX="$CTX"
HERMES_DIR="${HERMES_CONFIG_DIR:-$HOME/.hermes}"
SKILL_SRC="$ROOT/docs/hermes-overnight-skill.md"
SKILL_DST="$HERMES_DIR/skills/overnight-coding-autopilot.md"

mkdir -p "$HERMES_DIR" "$HERMES_DIR/skills"

ENV_FILE="$HERMES_DIR/.env"
touch "$ENV_FILE"
upsert() {
  local key="$1" val="$2"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    grep -v "^${key}=" "$ENV_FILE" >"${ENV_FILE}.tmp" || true
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
  fi
  echo "${key}=${val}" >>"$ENV_FILE"
}
upsert HERMES_API_TIMEOUT "${HERMES_API_TIMEOUT:-1800}"
upsert OLLAMA_HOST "$HOST_PORT"
upsert OLLAMA_MODEL "$MODEL"

# Hermes versions differ in config layout — write both common shapes.
cat >"$HERMES_DIR/config.yaml" <<EOF
# Generated by Autocode hermes/configure_local_primary.sh — local Ollama primary
model:
  default: "${MODEL}"
  provider: custom
  base_url: "${BASE_URL}"
  api_key: "ollama"
  context_length: ${CTX}
  ollama_num_ctx: ${CTX}
  max_tokens: 8192

# Keep paid fallbacks off until Phase 2b
fallback_providers: []
EOF

# Also keep stub for older docs / merge tools
cp "$ROOT/hermes/config.stub.yaml" "$HERMES_DIR/autocode.stub.yaml"
# Refresh stub to match .env
sed -i.bak \
  -e "s|base_url:.*|base_url: ${BASE_URL}|" \
  -e "s|model: coder-64k|model: ${MODEL}|" \
  -e "s|ollama_num_ctx:.*|ollama_num_ctx: ${CTX}|" \
  "$HERMES_DIR/autocode.stub.yaml" 2>/dev/null || true
rm -f "$HERMES_DIR/autocode.stub.yaml.bak"

if [[ -f "$SKILL_SRC" ]]; then
  cp "$SKILL_SRC" "$SKILL_DST"
  echo "Installed overnight skill → $SKILL_DST"
fi

echo "Wrote $HERMES_DIR/config.yaml"
echo "  base_url=$BASE_URL"
echo "  model=$MODEL"
echo "  ctx=$CTX"
echo
echo "Smoke (optional interactive):"
echo "  hermes chat -q \"Create a file /tmp/autocode-hermes-smoke.txt containing OK\""
echo "Next: ./scripts/smoke_hermes.sh"
